version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  producer:
    build:
      context: ./producer
      dockerfile: producer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./producer/csvs/:/csvs/
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
    #     interval: 10s
    #     timeout: 5s
    #     retries: 10

  consumer_post:
    build:
      context: ./consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=1
      - QUEUE_TO_READ=post_queue
      - QUEUES_TO_WRITE=queue_test_post

  consumer_comment:
    build:
      context: ./consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=2
      - QUEUE_TO_READ=comments_queue
      - QUEUES_TO_WRITE=queue_test_comments