version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  producer:
    build:
      context: ./producer
      dockerfile: producer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./producer/csvs/:/csvs/

  consumer_post:
    build:
      context: workers/consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=1
      - QUEUE_TO_READ=post_queue
      - QUEUES_TO_WRITE=queue_map_remove_columns|queue_map_remove_columns_3

  consumer_comment:
    build:
      context: workers/consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=2
      - QUEUE_TO_READ=comments_queue
      - QUEUES_TO_WRITE=queue_filter_deleted_removed

  map_remove_columns:
    build:
      context: workers/map_remove_columns
      dockerfile: map_remove_columns.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns
      - QUEUES_TO_WRITE=queue_reduce_agg_scores

  reduce_agg_scores:
    build:
      context: workers/reduce_agg_scores
      dockerfile: reduce_agg_scores.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_agg_scores
      - QUEUES_TO_WRITE=queue_reduce_avg_score

  reduce_avg_scores:
    build:
      context: workers/reduce_avg_scores
      dockerfile: reduce_avg_scores.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_avg_score
      - QUEUES_TO_WRITE=queue_response|queue_response_url

  filter_deleted_removed:
    build:
      context: workers/filter_deleted_removed
      dockerfile: filter_deleted_removed.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_filter_deleted_removed
      - QUEUES_TO_WRITE=queue_map_remove_columns_2

  map_remove_columns_2:
    build:
      context: workers/map_remove_columns_2
      dockerfile: map_remove_columns_2.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns_2
      - QUEUES_TO_WRITE=queue_join

  map_remove_columns_3:
    build:
      context: workers/map_remove_columns_3
      dockerfile: map_remove_columns_3.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns_3
      - QUEUES_TO_WRITE=queue_join_2

  join:
    build:
      context: workers/join
      dockerfile: join.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ_2=queue_join
      - QUEUE_TO_READ_3=queue_join_2
      - QUEUES_TO_WRITE=queue_filter_body_student|queue_map_remove_columns_4

#  map_remove_columns_4:
#    build:
#      context: workers/map_remove_columns_4
#      dockerfile: map_remove_columns_34.dockerfile
#    restart: on-failure
#    depends_on:
#      - rabbitmq
#    links:
#      - rabbitmq
#    environment:
#      - PYTHONUNBUFFERED=1
#      - QUEUE_TO_READ=queue_map_remove_columns_4
#      - QUEUES_TO_WRITE=queue_reduce_agg_sentiment

  filter_body_student:
    build:
      context: workers/filter_body_student
      dockerfile: filter_body_student.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_filter_body_student
      - QUEUES_TO_WRITE=queue_filter_score_mayor_avg

  filter_score_mayor_avg:
    build:
      context: workers/filter_score_mayor_avg
      dockerfile: filter_score_mayor_avg.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ_AVG=queue_response_url
      - QUEUE_TO_READ_FILTER=queue_filter_score_mayor_avg
      - QUEUES_TO_WRITE=queue_response_2