version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  producer:
    build:
      context: ./producer
      dockerfile: producer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./producer/csvs/:/csvs/
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
    #     interval: 10s
    #     timeout: 5s
    #     retries: 10

  consumer_post:
    build:
      context: workers/consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=1
      - QUEUE_TO_READ=post_queue
      - QUEUES_TO_WRITE=queue_map_remove_columns

  consumer_comment:
    build:
      context: workers/consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=2
      - QUEUE_TO_READ=comments_queue
      - QUEUES_TO_WRITE=queue_test_comments

  map_remove_columns:
    build:
      context: workers/map_remove_columns
      dockerfile: map_remove_columns.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns
      - QUEUES_TO_WRITE=queue_reduce_agg_scores

  reduce_agg_scores:
    build:
      context: workers/reduce_agg_scores
      dockerfile: reduce_agg_scores.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_agg_scores
      - QUEUES_TO_WRITE=queue_reduce_avg_score

  reduce_avg_scores:
    build:
      context: workers/reduce_avg_scores
      dockerfile: reduce_avg_scores.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_avg_score
      - QUEUES_TO_WRITE=queue_response

