version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  producer:
    build:
      context: ./producer
      dockerfile: producer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./producer/csvs/:/csvs/
      - ./producer/meme/:/meme/
      - ./middleware/:/middleware/

  consumer_post:
    build:
      context: workers/consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=1
      - QUEUE_TO_READ=post_queue
      - QUEUES_TO_WRITE=queue_map_remove_columns|queue_map_remove_columns_3
    volumes:
      - ./middleware/:/middleware/

  consumer_comment:
    build:
      context: workers/consumer
      dockerfile: consumer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=2
      - QUEUE_TO_READ=comments_queue
      - QUEUES_TO_WRITE=queue_filter_deleted_removed
    volumes:
      - ./middleware/:/middleware/

  map_remove_columns:
    build:
      context: workers/map_remove_columns
      dockerfile: map_remove_columns.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns
      - QUEUES_TO_WRITE=queue_reduce_agg_scores
    volumes:
      - ./middleware/:/middleware/

  reduce_agg_scores:
    build:
      context: workers/reduce_agg_scores
      dockerfile: reduce_agg_scores.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_agg_scores
      - QUEUES_TO_WRITE=queue_reduce_avg_score
    volumes:
      - ./middleware/:/middleware/

  reduce_avg_scores:
    build:
      context: workers/reduce_avg_scores
      dockerfile: reduce_avg_scores.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_avg_score
      - QUEUES_TO_WRITE=queue_response|queue_response_url
    volumes:
      - ./middleware/:/middleware/

  filter_deleted_removed:
    build:
      context: workers/filter_deleted_removed
      dockerfile: filter_deleted_removed.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_filter_deleted_removed
      - QUEUES_TO_WRITE=queue_map_remove_columns_2
    volumes:
      - ./middleware/:/middleware/

  map_remove_columns_2:
    build:
      context: workers/map_remove_columns_2
      dockerfile: map_remove_columns_2.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns_2
      - QUEUES_TO_WRITE=queue_join
    volumes:
      - ./middleware/:/middleware/

  map_remove_columns_3:
    build:
      context: workers/map_remove_columns_3
      dockerfile: map_remove_columns_3.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns_3
      - QUEUES_TO_WRITE=queue_join_2
    volumes:
      - ./middleware/:/middleware/

  join:
    build:
      context: workers/join
      dockerfile: join.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ_2=queue_join
      - QUEUE_TO_READ_3=queue_join_2
      - QUEUES_TO_WRITE=queue_filter_body_student|queue_map_remove_columns_4
    volumes:
      - ./middleware/:/middleware/

  filter_body_student:
    build:
      context: workers/filter_body_student
      dockerfile: filter_body_student.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_filter_body_student
      - QUEUES_TO_WRITE=queue_filter_score_mayor_avg
    volumes:
      - ./middleware/:/middleware/

  filter_score_mayor_avg:
    build:
      context: workers/filter_score_mayor_avg
      dockerfile: filter_score_mayor_avg.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ_AVG=queue_response_url
      - QUEUE_TO_READ_FILTER=queue_filter_score_mayor_avg
      - QUEUES_TO_WRITE=queue_response_2
    volumes:
      - ./middleware/:/middleware/

  map_remove_columns_4:
    build:
      context: workers/map_remove_columns_4
      dockerfile: map_remove_columns_4.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns_4
      - QUEUES_TO_WRITE=queue_reduce_agg_sentiment
    volumes:
      - ./middleware/:/middleware/

  reduce_agg_sentiment:
    build:
      context: workers/reduce_agg_sentiment
      dockerfile: reduce_agg_sentiment.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_agg_sentiment
      - QUEUES_TO_WRITE=queue_reduce_post_id
    volumes:
      - ./middleware/:/middleware/

  reduce_post_id:
    build:
      context: workers/reduce_post_id
      dockerfile: reduce_post_id.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_reduce_post_id
      - QUEUES_TO_WRITE=queue_find_max_sent_avg
    volumes:
      - ./middleware/:/middleware/

  find_max_sent_avg:
    build:
      context: workers/find_max_sent_avg
      dockerfile: find_max_sent_avg.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_find_max_sent_avg
      - QUEUES_TO_WRITE=queue_map_remove_columns_5
    volumes:
      - ./middleware/:/middleware/

  map_remove_columns_5:
    build:
      context: workers/map_remove_columns_5
      dockerfile: map_remove_columns_5.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_map_remove_columns_5
      - QUEUES_TO_WRITE=queue_download_meme
    volumes:
      - ./middleware/:/middleware/

  download_meme:
    build:
      context: workers/download_meme
      dockerfile: download_meme.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - QUEUE_TO_READ=queue_download_meme
      - QUEUES_TO_WRITE=queue_response_3
    volumes:
      - ./middleware/:/middleware/
